#sdk: "/Users/bhanu/.gems/gems/rhodes-3.2.1"
sdkversion: 3.2.1
name: store-push-rhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator4.3
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.store-push-rhodes
  BundleURLScheme: store-push-rhodes
wp:
  productid: 'fa8254e0-e714-012e-2d16-60c54789b794'
symbian:
  uid: '0xec5934b5'
android:
  version: 2.3.3
  push:
    sender: rhoc2dm@gmail.com

extensions: ["json", "another-extension"]
capabilities:
  - push
